### ISSUE TITLE
Build fails on Nightly Rust

### ISSUE THREAD

**Issue by lmaotrigine** [lmaotrigine/heartbeat#8]
This is due to a compiler bug, originally filed in rust-lang/rust#117598.

This issue is left here for reference and will be closed once it is resolved upstream.

**Comment by HTGAzureX1212** [comment]
The issue has been closed upstream.

**Comment by lmaotrigine** [comment]
yup, just noticed, thanks!

Closed by https://github.com/rust-lang/rust/commit/fab1054e1742790c22ccc92a625736d658363677
